name: CI

on:
  push:
    branches: [ feature/set-up-github-actions ]
  pull_request:
    branches: [ feature/set-up-github-actions ]
  schedule:
  - cron: "0 9 * * 1-5"

jobs:
  test:
    name: UnitTests
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 11 Pro']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Installing Pods
        run : pod install
      - name: Run Unit Tests
        run: |
          # ls -al
          # pwd
          # ls -al
          xcodebuild clean test -project SpaceX.xcworkspace -scheme SpaceX
