name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  schedule:
  - cron: "0 9 * * 1-5"

jobs:
  test:
    name: UnitTests
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 11 Pro']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Testing
        run: |
          cd SpaceX
          xcodebuild clean test -project SpaceX.xcworkspace -scheme SpaceX
